In [1]:
import pandas as pd
import re
import time

In [2]:
stations = {
    'sakashita': 'area=4&pref=22&id=1198',
    'ochiaigawa': 'area=4&pref=22&id=1197',
    'nakatsugawa': 'area=4&pref=22&id=1196',
    'minosakamoto': 'area=4&pref=22&id=1195',
    'ena': 'area=4&pref=22&id=1194',
    'takenami': 'area=4&pref=22&id=1193',
    'kamado': 'area=4&pref=22&id=1192',
    'mizunami': 'area=4&pref=22&id=1191',
    'tokishi': 'area=4&pref=22&id=1190',
    'tajimi': 'area=4&pref=22&id=1189',
    'kokoke': 'area=4&pref=22&id=1188',
    'jokoji': 'area=4&pref=24&id=41',
    'kozoji': 'area=4&pref=24&id=40',
    'jinryo': 'area=4&pref=24&id=39',
    'kasugai': 'area=4&pref=24&id=38',
    'kachigawa':'area=4&pref=24&id=37',
    'shinmoriyama': 'area=4&pref=24&id=36',
    'ozone': 'area=4&pref=24&id=35',
    'chikusa': 'area=4&pref=24&id=34',
    'tsurumai': 'area=4&pref=24&id=33',
    'kanayama': 'area=4&pref=24&id=32',
    'nagoya': 'area=4&pref=24&id=31'
}

In [3]:
url = 'https://storestrategy.jp/?category=1&'+list(stations.values())[0]
fetched_dataframe = pd.read_html(url)

In [4]:
fetched_dataframe[0]

               0          1          2          3    4
0            NaN     500m圏内      1km圏内      2km圏内   絞込
1        乗降客数（日）    1,127 人        NaN        NaN  NaN
2           人口総数     1,561人     3,184人     4,691人  NaN
3           男性人口       750人     1,526人     2,248人  NaN
4         男性人口比率     48.05%     47.93%     47.92%  NaN
5        0～14歳人口       200人       401人       599人  NaN
6       15～64歳人口       842人     1,745人     2,581人  NaN
7        65歳以上人口       518人     1,049人     1,516人  NaN
8           昼間人口     1,634人     3,234人     4,951人  NaN
9            世帯数      528世帯    1,106世帯    1,594世帯  NaN
10         1人世帯数      106世帯      227世帯      310世帯  NaN
11        1人世帯比率        20%     20.52%     19.45%  NaN
12        小売事業所数        43件        61件        65件  NaN
13    小売業年間商品販売額  333,493万円  457,115万円  457,418万円  NaN
14       全産業事業所数       143件       219件       292件  NaN
15       飲食店事業所数        14件        22件        26件  NaN
16         生徒学生数         0人       272人       836人  NaN
17    0～9歳人口(比率)      8.27%      8.42%      8.16%  NaN
18  10～19歳人口(比率)      8.91%      8.23%      8.73%  NaN
19  20～29歳人口(比率)      7.44%      7.48%      7.37%  NaN
20  30～39歳人口(比率)     10.38%      10.9%     10.56%  NaN
21  40～49歳人口(比率)     11.35%     10.77%     10.92%  NaN
22  50～59歳人口(比率)     11.99%     12.21%     13.03%  NaN
23  60～69歳人口(比率)     15.06%     16.41%     16.06%  NaN
24  70～79歳人口(比率)     14.81%     14.28%     14.12%  NaN
25   80歳以上人口(比率)     11.79%      11.3%     11.05%  NaN
26  買回り品(事業所数比率)     41.86%     44.26%     46.15%  NaN
27  最寄り品(事業所数比率)     46.51%      45.9%     44.62%  NaN
28      全産業従業者総数       928人     1,499人     1,978人  NaN

In [5]:
inds = list(fetched_dataframe[0].iloc[1:, 0])
cols = stations
info = pd.DataFrame(index=inds, columns=cols)
info_far = pd.DataFrame(index=inds, columns=cols)
#info

In [6]:
for i in range(len(stations)):
    if i in [0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 13, 16]:
        url = 'https://storestrategy.jp/?category=1&'+list(stations.values())[i]
        fetched_dataframe = pd.read_html(url)
        station = fetched_dataframe[0]
        info.iloc[:, i] = station.iloc[1:, 1].values
        info_far.iloc[:, i] = station.iloc[2:, 3].values
        time.sleep(5)
    else:
        url = 'https://storestrategy.jp/?category=1&'+list(stations.values())[i]
        fetched_dataframe = pd.read_html(url)
        station = fetched_dataframe[0]
        info.iloc[:, i] = station.iloc[2:, 1].values
        info_far.iloc[:, i] = station.iloc[3:, 3].values
        time.sleep(5)

In [7]:
#info.isnull().sum()

In [ ]:
info_far.loc['乗降客数（日）'] = info.loc['乗降客数（日）']

In [1]:
info.to_csv('input/station_data500m.csv')
info_far.to_csv('input/station_data2km.csv')

NameError: name 'info' is not defined